development:
  adapter: postgresql
  encoding: utf8
  database: hotjams
  pool: 5
  username: postgres
  password: pi1413

test:
  adapter: postgresql
  encoding: utf8
  database: hotjams
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: hotjams
  pool: 5
  username:
  password: